[theme]
primaryColor = "#7B2D8B"
backgroundColor = "#F5F0FF"
secondaryBackgroundColor = "#EDE7F6"
textColor = "#1A1A2E"
font = "sans serif"

[server]
port = 8502
headless = true
baseUrlPath = "MonitoreoRANsharing_Entel"
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
